[package]
name = "redis-custom-hashmap"
version = "0.1.0"
edition = "2021"
description = "Redis module for custom hashmap storage"

[lib]
crate-type = ["cdylib"]

[dependencies]
redis-module = { version = "2.0.7" }
libc = "0.2"
